Repository nextcloud/files_automatedtagging, pull requests merged in 2022-08, with the labels that each got.

#573 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#575 Update npm and node engines versions
  package.json
Labels: dependencies

#576 Run npm audit fix
  package-lock.json
Labels: bug, 4. to release

#582 [stable24] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#581 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#584 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#587 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#588 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
