Repository nextcloud/files_automatedtagging, pull requests merged in 2022-09, with the labels that each got.

#590 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#591 maintenance and tech debt
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  composer.lock
  lib/AppInfo/Application.php
  lib/Listener/CacheListener.php
  lib/Listener/RegisterFlowOperationsListener.php
  lib/Operation.php
  lib/Settings/Admin.php
  tests/OperationTest.php
Labels: 3. to review, technical debt

#592 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#593 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#594 Adjust testing matrix for Nextcloud 25 on stable25
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-christophwurst-nextcloud.yml
Labels: 4. to release

#597 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#596 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
