Repository nextcloud/files_automatedtagging, pull requests merged in 2023-03, with the labels that each got.

#691 chore(CI): Adjust testing matrix for Nextcloud 26 on stable26
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 4. to release

#692 chore: Add Nextcloud 27 support on master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/update-nextcloud-ocp.yml
  appinfo/info.xml
  package.json
Labels: 4. to release

#695 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#696 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#705 fix: Check tag attribute
  composer.json
  lib/Operation.php
  tests/OperationTest.php
Labels: bug, 3. to review, backport-request

#699 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#703 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#704 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#711 [stable21] fix: Check tag attribute
  .github/workflows/phpunit.yml
  CHANGELOG.md
  appinfo/info.xml
  lib/Operation.php
  tests/OperationTest.php
Labels: bug, 4. to release

#709 [stable23] fix: Check tag attribute
  CHANGELOG.md
  appinfo/info.xml
  lib/Operation.php
  tests/OperationTest.php
Labels: bug, 4. to release

#715 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#714 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
