Repository nextcloud/files_automatedtagging, pull requests merged in 2023-02, with the labels that each got.

#677 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#679 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#680 v1.14.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#681 v1.15.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 4. to release

#683 Bump to @nextcloud/vue@^7.6.0 and move to the new NcSelectTags component
  package-lock.json
  package.json
  src/Tag.vue
Labels: bug, 3. to review, backport-request

#682 v1.16.0
  CHANGELOG.md
Labels: 3. to review

#687 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#686 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#685 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#690 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
