Repository nextcloud/files_automatedtagging, pull requests merged in 2023-05, with the labels that each got.

#736 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#735 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#734 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#739 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#740 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#741 Release 1.17.0
  CHANGELOG.md
  composer.json
Labels: 3. to review

#746 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#745 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#749 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#748 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-compile.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/update-nextcloud-ocp.yml
  tests/OperationTest.php
Labels: 3. to review, dependencies, automated
