Repository nextcloud/files_automatedtagging, pull requests merged in 2024-05, with the labels that each got.

#912 Add SPDX header
  .github/workflows/reuse.yml
  .php-cs-fixer.dist.php
  .reuse/dep5
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  appinfo/info.xml
  docs/screenshot.png.license
  img/app.svg
  lib/AppInfo/Application.php
  lib/Listener/CacheListener.php
  lib/Listener/RegisterFlowOperationsListener.php
  lib/Operation.php
  lib/Settings/Admin.php
  src/Tag.vue
  src/main.js
  tests/OperationTest.php
  tests/bootstrap.php
Labels: 3. to review, technical debt

#923 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#918 Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
  README.md
Labels: dependencies

#927 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#928 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#929 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#930 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#933 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#936 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#935 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
