Repository nextcloud/files_automatedtagging, pull requests merged in 2024-03, with the labels that each got.

#881 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#882 chore(release): Add changelog for 1.19.0
  CHANGELOG.md
Labels: 4. to release

#883 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#886 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#887 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#885 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#888 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#891 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#892 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#896 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#900 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
