Repository nextcloud/files_automatedtagging, pull requests merged in 2024-07, with the labels that each got.

#956 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#958 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#959 Migrate REUSE to TOML
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#963 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#961 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/command-compile.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#964 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#965 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#962 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#970 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#969 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#971 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#972 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
